name: Terraform CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
  TF_WORKING_DIR: terraform-demo

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Authenticate to GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" | base64 -d > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project $PROJECT_ID

      - name: Terraform Init
        run: |
          cd $TF_WORKING_DIR
          terraform init -backend-config="bucket=$TF_STATE_BUCKET" -backend-config="prefix=terraform/state"

      - name: Terraform Plan
        run: |
          cd $TF_WORKING_DIR
          terraform plan -input=false

  terraform-apply:
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Authenticate to GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" | base64 -d > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project $PROJECT_ID

      - name: Terraform Apply
        run: |
          cd $TF_WORKING_DIR
          terraform apply -auto-approve
